let data = [
    {
        id: 0,
        title: "The Godfather",
        director: "Francis Ford Coppola",
        metascore: 100,
        genre: "Drama",
        description: "War hero Michael is the prodigal son of aging but fearsome crime patriarch Don Vito Corleone. When Michael returns home only to be thrust into an all-too-familiar world of hitmen, corrupt cops, and simmering mafia rivalries, he is forced to choose between his own path and the Corleone family legacy.",
        descriptionTurk: "Don Corleone’nin kızı Connie’nin düğününde, ailenin en küçük oğlu ve bir savaş gazisi olan Michael babasıyla barışır. Bir suikast girişimi, Don’u artık işleri yönetemeyecek duruma düşürünce, ailenin başına Michael ve ağabeyi Sonny geçer. Danışmanları Tom Hagen’in de yardımlarıyla diğer ailelere savaş açan Corleone ailesi, eski moda yöntemleri de değiştirmeye başlar.",
    },
    {
        id: 1,
        title: "12 Angry Men",
        director: "Sidney Lumet",
        metascore: 97,
        genre: "Crime",
        description: "A jury holdout attempts to prevent a miscarriage of justice by forcing his colleagues to reconsider the evidence.",
        descriptionTurk: "12 Öfkeli Adam, cinayetle suçlanan bir genç ile ilgili karar vermekle yükümlü 12 jüri üyesinin karar verme sürecini konu ediyor.",
    },
    {
        id: 2,
        title: "Whiplash",
        director: "Damien Chazelle",
        metascore: 89,
        genre: "Drama",
        description: "A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student's potential.",
        descriptionTurk: "Küçük yaşlardan itibaren bateri çalmaya başlayan Andrew, işinde tam anlamıyla bir usta olmak ister. Bir gün, okulun en sert hocalarından biri olan caz duayeni Terence Fletcher'ın dikkatini çeker. Fletcher Andrew'ü okulun en parlak öğrencilerinin seçildiği ve sürekli yeni yarışmalara hazırlanan 'studio band' ekibine seçer. Başarısı kadar acımasızlığıyla da ün yapmış olan Fletcher, Andrew'un kapasitesinin sonuna kadar kullanmadan asla başarmış saymayacaktır.",
    },
    {
        id: 3,
        title: "V for Vendetta",
        director: "James McTeigue",
        metascore: 62,
        genre: "Action",
        description: "In a future British tyranny, a shadowy freedom fighter, known only by the alias of \"V\", plots to overthrow it with the help of a young woman.",
        descriptionTurk: "Türlü yasaklar ve engellerle idare edilen halk, şiddet yanlısı bir konuma gelmiştir. Bu kargaşanın orta yerinde görünen gizemli V, belaya bulaşmış masum bir kadın olan Evey’i kurtarır. Ancak bu kurtarış, tam da ulusun kurtuluşunu temsil eder çünkü onun davranışı aslında toplumun uyanışını tetikleyen ve başkaldırıyı başlatan unsurdur.",
    },
    {
        id: 4,
        title: "Wall-E",
        director: "Andrew Stanton",
        metascore: 95,
        genre: "Animation",
        description: "In the distant future, a small waste-collecting robot inadvertently embarks on a space journey that will ultimately decide the fate of mankind.",
        descriptionTurk: "İnsanoğlu aşırı kirlenme sebebiyle Dünya’yı terk edip başka bir gezegende yaşamaya başlamıştır. Çöplerle çevrili dünyayı temizleme görevi sevimli bir robota, Vol.i’ye verilir. İnsanoğlunun bıraktığı çöplerden kendine yeni bir dünya yaratan yalnız Vol.i’nin yalnızlığı, başka bir robot olan Eve’nın gelmesiyle son bulur.",
    },
    {
        id: 5,
        title: "American History X",
        director: "Tony Kaye",
        metascore: 62,
        genre: "Crime",
        description: "A former neo-nazi skinhead tries to prevent his younger brother from going down the same wrong path that he did.",
        descriptionTurk: "Babasının uyuşturucu satıcısı bir zenci tarafından öldürülmesinden sonra Derek faşist bir çetenin önemli bir üyesi haline gelmiştir. Babasının ölümünün intikamını bu örgütün, kendileri gibi olmayanlara karşı yaptığı saldırılar ve tacizlerle almaya çalışan Derek, bir gün, arabasını çalmaya çalışan iki zenciyi öldürür ve hapse girer. Bu süreçte küçük kardeşi Danny de ağabeyinin izinden gitmeyi seçer. Derek hapiste geçirdiği süre boyunca bambaşka bir adam olmuş, yaptığı hatalardan pişmanlık duymuştur.",
    },
    {
        id: 6,
        title: "Memento",
        director: "Christopher Nolan",
        metascore: 81,
        genre: "Thriller",
        description: "A man juggles searching for his wife's murderer and keeping his short-term memory loss from being an obstacle.",
        descriptionTurk: "Kısa süreli hafıza kaybı olan bir adamın karısını öldürenleri bulma çabasını konu ediyor.",
    },
    {
        id: 7,
        title: "Black Swan",
        director: "Darren Aronofsky",
        metascore: 79,
        genre: "Drama",
        description: "A committed dancer wins the lead role in a production of Tchaikovsky's \"Swan Lake\" only to find herself struggling to maintain her sanity.",
        descriptionTurk: "Genç bir kadın olan Nina, yetenekli bir balerindir. Bale yönetmeni Thomas Leroy, sahneye koyduğu Kuğu Gölü Balesi’nin baş dansçısını yeni sezonda değiştirmeye karar verir. Zarif, masum ve saf Beyaz Kuğu ile kötülüğün, şehvetin ve bilinmezliğin temsilcisi Siyah Kuğu'yu aynı anda canlandırabilecek bir balerin arayan yönetmenin ilk tercihi Nina olur. Ancak rolü almak için elinden geleni yapan Nina’nın karşısında güçlü bir rakibi vardır.",
    },
    {
        id: 8,
        title: "The Truman Show",
        director: "Peter Weir",
        metascore: 90,
        genre: "Sci-Fi",
        description: "An insurance salesman/adjuster discovers his entire life is actually a television show.",
        descriptionTurk: "Güzel bir eşe ve mutlu bir hayata sahip olan Truman, bir gün öldüğünü zannettiği babasını bir gün caddede gördüğü ana kadar hayatı olduğu gibi yaşar. Babasını gördüğüne emindir ancak adam bir anda ortalıktan kaybolmuştur. İlerleyen günlerde çeşitli gizemli anlar yaşayan Truman bir şeylerin yolunda gitmediğini fark edecek, sahip olduğu hayatın gerçek olup olmadığını anlamaya çalışacaktır.",
    },
    {
        id: 9,
        title: "Vicky Cristina Barcelona",
        director: "Woody Allen",
        metascore: 70,
        genre: "Romance",
        description: "Two girlfriends on a summer holiday in Spain become enamored with the same painter, unaware that his ex-wife, with whom he has a tempestuous relationship, is about to re-enter the picture.",
        descriptionTurk: "Amerikalı Vicky ve Cristina, İspanya'da geçirecekleri bir yaz tatilinde, karşılarına çıkan gizemli bir İspanyol sanatçıdan etkileneceklerdir. Gösterişli sanatçı (Javier Bardem) ve onun güzel fakat 'arıza' eski eşi (Penélope Cruz) ile tehlikeli sularda yüzeceklerdir. Vicky (Rebecca Hall) evlenmek üzere olan ancak muhafazakar ve tutucu bir kadındır. Cristina (Scarlett Johansson) ise cinsel maceralara meraklı, zihni açık, özgür ruhlu bir kadındır. Kaderleri kesişen üç insan arasında doğan yasak aşk ilişkisi kaotik sonuçlar doğuracaktır.",
    }
];

export default data;
